import React from "react";
import { createRoot } from "react-dom/client";
import { Phone, MessageCircle, Zap, ShieldCheck, MapPin, Store, Bike, Utensils, Coffee, ShoppingBag, Package, ArrowLeft, Menu, X } from "lucide-react";
import "./styles.css";

type Page = "home" | "about" | "services" | "join" | "contact";
const PHONE = "01000000000";

function App(){
 const [page,setPage]=React.useState<Page>("home"); const [menu,setMenu]=React.useState(false);
 const nav:[Page,string][]=[["home","الرئيسية"],["about","عن فالسريع"],["services","خدماتنا"],["join","انضم إلينا"],["contact","تواصل معنا"]];
 const go=(p:Page)=>{setPage(p);setMenu(false);window.scrollTo({top:0,behavior:"smooth"});};
 return <div className="app">
 <header className="nav"><button className="brand" onClick={()=>go("home")}><span className="brand-mark">F</span><span>فالسريع</span></button><nav>{nav.map(([p,n])=><button className={page===p?"active":""} key={p} onClick={()=>go(p)}>{n}</button>)}</nav><div className="nav-actions"><a className="call-mini" href={"tel:"+PHONE}><Phone size={17}/> اطلب الآن</a><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
 {menu&&<div className="mobile-nav">{nav.map(([p,n])=><button key={p} onClick={()=>go(p)}>{n}</button>)}</div>}
 <main>{page==="home"&&<Home go={go}/>} {page==="about"&&<About/>} {page==="services"&&<Services/>} {page==="join"&&<Join/>} {page==="contact"&&<Contact/>}</main>
 <footer><div><button className="brand" onClick={()=>go("home")}><span className="brand-mark">F</span><span>فالسريع</span></button><p>اطلبها… توصل فالسريع.</p></div><div className="footer-links">{nav.map(([p,n])=><button key={p} onClick={()=>go(p)}>{n}</button>)}</div><small>© {new Date().getFullYear()} فالسريع — جميع الحقوق محفوظة</small></footer>
 </div>
}
function Home({go}:{go:(p:Page)=>void}){return <>
<section className="hero"><div className="hero-glow"></div><div className="hero-copy"><span className="eyebrow">قريبًا في مدينتك ⚡</span><h1>كل اللي محتاجه…<strong>يوصلك فالسريع.</strong></h1><p>خدمة توصيل محلية بسيطة وسريعة. حاليًا اطلب بسهولة عبر الهاتف أو واتساب.</p><div className="hero-buttons"><a className="btn primary" href={"tel:"+PHONE}><Phone/> اطلب عبر الهاتف</a><a className="btn secondary" href="https://wa.me/" target="_blank"><MessageCircle/> واتساب</a></div><div className="quick"><span><Zap/> أسرع</span><span><ShieldCheck/> موثوق</span><span><MapPin/> أقرب لك</span></div></div><div className="hero-visual"><div className="speed-lines"></div><div className="orb"></div><div className="rider-card"><Bike size={120}/><b>فالسريع</b><small>ON THE WAY</small></div></div></section>
<section className="section"><div className="section-head"><span>لماذا فالسريع؟</span><h2>بسيطة… وسريعة… وقريبة منك.</h2></div><div className="grid three">{[[Zap,"سرعة","لأن وقتك مهم."],[ShieldCheck,"ثقة","نهتم بطلبك حتى يصل."],[MapPin,"قريب منك","خدمة محلية تعرف منطقتك."]].map(([Icon,title,txt]:any)=><article className="card" key={title}><Icon/><h3>{title}</h3><p>{txt}</p></article>)}</div></section>
<section className="section dark-band"><div className="section-head"><span>خدماتنا</span><h2>إيه اللي نقدر نوصله؟</h2></div><div className="grid four">{[[Utensils,"مطاعم"],[Coffee,"كافيهات"],[ShoppingBag,"محلات"],[Package,"احتياجاتك"]].map(([Icon,title]:any)=><article className="service-card" key={title}><Icon/><b>{title}</b></article>)}</div><button className="text-link" onClick={()=>go("services")}>اكتشف خدماتنا <ArrowLeft size={18}/></button></section>
<section className="coming"><div><span className="eyebrow">COMING SOON</span><h2>تطبيق فالسريع قريبًا 📱</h2><p>نعمل حاليًا على تجربة أسهل للطلبات والمتابعة.</p></div><div className="phone-mock"><div className="notch"></div><span className="brand-mark">F</span><b>فالسريع</b><small>COMING SOON</small></div></section>
<section className="cta"><h2>محتاج حاجة؟</h2><p>اتصل بنا الآن وخلي طلبك يوصل فالسريع.</p><a className="btn primary" href={"tel:"+PHONE}><Phone/> اتصل الآن</a></section></>}
function About(){return <PageHero eyebrow="عن فالسريع" title={<>أكثر من مجرد <strong>توصيل.</strong></>} text="فالسريع مشروع محلي هدفه يجعل الوصول لاحتياجاتك أسهل وأسرع." ><section className="section"><div className="grid three">{[[Zap,"مهمتنا","نجعل التوصيل أبسط وأسرع."],[ShieldCheck,"وعدنا","الوضوح والاهتمام بكل طلب."],[MapPin,"رؤيتنا","نبدأ محليًا ونتطور خطوة بخطوة."]].map(([I,t,d]:any)=><article className="card" key={t}><I/><h3>{t}</h3><p>{d}</p></article>)}</div></section><section className="section story"><div><span>قصتنا</span><h2>بداية صغيرة… وطموح كبير.</h2></div><p>نؤمن أن المشاريع الناجحة تبدأ بحل مشكلة حقيقية. لذلك نبدأ بخدمة بسيطة، نستمع للعملاء، ثم نطور التجربة بناءً على الاحتياج الحقيقي.</p></section></PageHero>}
function Services(){return <PageHero eyebrow="خدماتنا" title={<>كل اللي تحتاجه… <strong>نوصله لك.</strong></>} text="نبدأ بخدمات توصيل بسيطة، ونتوسع حسب احتياجات منطقتنا."><section className="section"><div className="grid three">{[[Utensils,"طلبات المطاعم","وجبتك من مكانك المفضل."],[Coffee,"الكافيهات","قهوة ومشروباتك."],[ShoppingBag,"طلبات المحلات","احتياجاتك من المحلات."],[Package,"طلبات متنوعة","حسب نطاق الخدمة."],[Store,"شركاء محليون","ندعم المحلات والمطاعم."],[Bike,"توصيل سريع","تجربة مباشرة وبسيطة."]].map(([I,t,d]:any)=><article className="card" key={t}><I/><h3>{t}</h3><p>{d}</p></article>)}</div></section></PageHero>}
function Join(){return <PageHero eyebrow="انضم إلينا" title={<>كبر مع <strong>فالسريع.</strong></>} text="سواء كنت تريد العمل كمندوب أو توسيع نشاطك كشريك."><section className="section"><div className="grid two"><article className="join-card"><Bike/><h2>انضم كمندوب</h2><p>فرصة للعمل بمرونة والمشاركة في بناء الخدمة.</p><button className="btn primary" onClick={()=>alert("نموذج التسجيل سيتم ربطه لاحقًا.")}>سجل كمندوب</button></article><article className="join-card"><Store/><h2>كن شريكًا</h2><p>اعرض نشاطك ووصل إلى عملاء أكثر.</p><button className="btn secondary" onClick={()=>alert("نموذج الشركاء سيتم ربطه لاحقًا.")}>سجل كشريك</button></article></div></section></PageHero>}
function Contact(){return <PageHero eyebrow="تواصل معنا" title={<>نحن <strong>قريبون منك.</strong></>} text="للطلبات والاستفسارات والتعاون، تواصل معنا بسهولة."><section className="section"><div className="grid two"><a className="contact-card" href={"tel:"+PHONE}><Phone/><div><b>اتصل بنا</b><span>{PHONE}</span></div></a><a className="contact-card" href="https://wa.me/" target="_blank"><MessageCircle/><div><b>واتساب</b><span>تواصل معنا مباشرة</span></div></a></div></section></PageHero>}
function PageHero({eyebrow,title,text,children}:{eyebrow:string,title:React.ReactNode,text:string,children:React.ReactNode}){return <><section className="page-hero"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></section>{children}<section className="cta"><h2>فالسريع… قريبًا أكثر.</h2><p>تابعنا لمعرفة آخر الأخبار والتحديثات.</p></section></>}

createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);