import React from "react";
import { createRoot } from "react-dom/client";
import { Phone, MessageCircle, Zap, ShieldCheck, MapPin, Store, Bike, Utensils, Coffee, ShoppingBag, Package, ArrowLeft, Menu, X, Users } from "lucide-react";
import "./styles.css";

type Page = "home" | "about" | "services" | "join" | "contact" | "privacy" | "terms";
type ContactItem = {label:string; value:string; type:"phone"|"whatsapp"};
type SocialItem = {label:string; url:string};
const SERVICE_AREA = "سيتم الإعلان عنها قريبًا";
const SOCIALS: SocialItem[] = [
  // أضف روابط الصفحات الرسمية هنا لاحقًا.
];
const CONTACTS: ContactItem[] = [
 {label:"الدعم والطلبات",value:"01032789566",type:"phone"},
 {label:"الدعم والطلبات",value:"01064589298",type:"phone"},
 {label:"واتساب فالسريع",value:"201032789566",type:"whatsapp"}
];
const PHONE = CONTACTS.find(x=>x.type==="phone")?.value ?? "";
const cleanPhone=(v:string)=>v.replace(/[^0-9]/g,"");
const contactHref=(c:ContactItem)=>c.type==="whatsapp"?`https://wa.me/${cleanPhone(c.value)}`:`tel:${cleanPhone(c.value)}`;

function App(){
 const [page,setPage]=React.useState<Page>("home"); const [menu,setMenu]=React.useState(false);
 const nav:[Page,string][]=[["home","الرئيسية"],["about","عن فالسريع"],["services","خدماتنا"],["join","انضم إلينا"],["contact","تواصل معنا"]];
 const go=(p:Page)=>{setPage(p);setMenu(false);window.scrollTo({top:0,behavior:"smooth"});};
 return <div className="app">
 <header className="nav"><button className="brand" onClick={()=>go("home")}><span className="brand-mark">F</span><span>فالسريع</span></button><nav>{nav.map(([p,n])=><button className={page===p?"active":""} key={p} onClick={()=>go(p)}>{n}</button>)}</nav><div className="nav-actions"><a className="call-mini" href={PHONE ? "tel:"+PHONE : "#contact"}><Phone size={17}/> اطلب الآن</a><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
 {menu&&<div className="mobile-nav">{nav.map(([p,n])=><button key={p} onClick={()=>go(p)}>{n}</button>)}</div>}
 <main>{page==="home"&&<Home go={go}/>} {page==="about"&&<About/>} {page==="services"&&<Services/>} {page==="join"&&<Join/>} {page==="contact"&&<Contact/>} {page==="privacy"&&<Legal title="سياسة الخصوصية" type="privacy"/>} {page==="terms"&&<Legal title="الشروط والأحكام" type="terms"/>}</main>
 <footer><div><button className="brand" onClick={()=>go("home")}><span className="brand-mark">F</span><span>فالسريع</span></button><p>اطلبها… توصل فالسريع.</p></div><div className="footer-links">{nav.map(([p,n])=><button key={p} onClick={()=>go(p)}>{n}</button>)}</div><div className="legal-links"><button onClick={()=>go("privacy")}>سياسة الخصوصية</button><span>•</span><button onClick={()=>go("terms")}>الشروط والأحكام</button></div><small>© {new Date().getFullYear()} فالسريع — جميع الحقوق محفوظة</small></footer>
 </div>
}
function Home({go}:{go:(p:Page)=>void}){return <>
<section className="hero"><div className="hero-glow"></div><div className="hero-copy"><span className="eyebrow">قريبًا في مدينتك ⚡</span><h1>كل اللي محتاجه…<strong>يوصلك فالسريع.</strong></h1><p>خدمة توصيل محلية بسيطة وسريعة. حاليًا اطلب بسهولة عبر الهاتف أو واتساب.</p><div className="hero-buttons"><a className="btn primary" href={PHONE ? "tel:"+PHONE : "#contact"}><Phone/> اطلب عبر الهاتف</a><a className="btn secondary" href={contactHref(CONTACTS.find(x=>x.type==="whatsapp")!)} target="_blank" rel="noreferrer"><MessageCircle/> واتساب</a></div><div className="quick"><span><Zap/> أسرع</span><span><ShieldCheck/> موثوق</span><span><MapPin/> أقرب لك</span></div></div><div className="hero-visual"><div className="speed-lines"></div><img className="hero-image" src="/images/hero-placeholder.svg" alt="صورة توصيل فالسريع" /><div className="image-label">صورة مؤقتة قابلة للاستبدال</div></div></section>
<section className="announcement"><span>⚡</span><p>الموقع في مرحلته التعريفية حاليًا — التطبيق ونظام الطلبات قريبًا.</p></section><section className="service-area"><MapPin/><span>منطقة الخدمة:</span><b>{SERVICE_AREA}</b></section><section className="section"><div className="section-head"><span>لماذا فالسريع؟</span><h2>بسيطة… وسريعة… وقريبة منك.</h2></div><div className="grid three">{[[Zap,"سرعة","لأن وقتك مهم."],[ShieldCheck,"ثقة","نهتم بطلبك حتى يصل."],[MapPin,"قريب منك","خدمة محلية تعرف منطقتك."]].map(([Icon,title,txt]:any)=><article className="card" key={title}><Icon/><h3>{title}</h3><p>{txt}</p></article>)}</div></section>
<section className="section dark-band"><div className="section-head"><span>خدماتنا</span><h2>إيه اللي نقدر نوصله؟</h2></div><div className="grid four">{[[Utensils,"مطاعم"],[Coffee,"كافيهات"],[ShoppingBag,"محلات"],[Package,"احتياجاتك"]].map(([Icon,title]:any)=><article className="service-card" key={title}><Icon/><b>{title}</b></article>)}</div><button className="text-link" onClick={()=>go("services")}>اكتشف خدماتنا <ArrowLeft size={18}/></button></section>
<section className="coming"><div><span className="eyebrow">COMING SOON</span><h2>تطبيق فالسريع قريبًا 📱</h2><p>نعمل حاليًا على تجربة أسهل للطلبات والمتابعة.</p></div><div className="phone-mock"><div className="notch"></div><img src="/images/app-placeholder.svg" alt="معاينة تطبيق فالسريع قريبًا" /></div></section>
<section className="cta"><h2>محتاج حاجة؟</h2><p>اختار الطريقة المناسبة وتواصل معنا مباشرة.</p><div className="hero-buttons center-buttons"><a className="btn primary" href={PHONE ? "tel:"+PHONE : "#contact"}><Phone/> اتصل الآن</a><a className="btn secondary" href={contactHref(CONTACTS.find(x=>x.type==="whatsapp")!)} target="_blank" rel="noreferrer"><MessageCircle/> واتساب</a></div></section></>}
function About(){return <PageHero eyebrow="عن فالسريع" title={<>أكثر من مجرد <strong>توصيل.</strong></>} text="فالسريع مشروع محلي هدفه يجعل الوصول لاحتياجاتك أسهل وأسرع." ><section className="section"><div className="grid three">{[[Zap,"مهمتنا","نجعل التوصيل أبسط وأسرع."],[ShieldCheck,"وعدنا","الوضوح والاهتمام بكل طلب."],[MapPin,"رؤيتنا","نبدأ محليًا ونتطور خطوة بخطوة."]].map(([I,t,d]:any)=><article className="card" key={t}><I/><h3>{t}</h3><p>{d}</p></article>)}</div></section><section className="section story"><div><span>قصتنا</span><h2>بداية صغيرة… وطموح كبير.</h2></div><p>نؤمن أن المشاريع الناجحة تبدأ بحل مشكلة حقيقية. لذلك نبدأ بخدمة بسيطة، نستمع للعملاء، ثم نطور التجربة بناءً على الاحتياج الحقيقي.</p></section></PageHero>}
function Services(){return <PageHero eyebrow="خدماتنا" title={<>كل اللي تحتاجه… <strong>نوصله لك.</strong></>} text="نبدأ بخدمات توصيل بسيطة، ونتوسع حسب احتياجات منطقتنا."><section className="section"><div className="grid three">{[[Utensils,"طلبات المطاعم","وجبتك من مكانك المفضل."],[Coffee,"الكافيهات","قهوة ومشروباتك."],[ShoppingBag,"طلبات المحلات","احتياجاتك من المحلات."],[Package,"طلبات متنوعة","حسب نطاق الخدمة."],[Store,"شركاء محليون","ندعم المحلات والمطاعم."],[Bike,"توصيل سريع","تجربة مباشرة وبسيطة."]].map(([I,t,d]:any)=><article className="card" key={t}><I/><h3>{t}</h3><p>{d}</p></article>)}</div>{SOCIALS.length>0&&<><h2 className="contact-title">تابعنا</h2><div className="social-list">{SOCIALS.map((s,i)=><a key={i} href={s.url} target="_blank" rel="noreferrer">{s.label}</a>)}</div></>}</section></PageHero>}
function Join(){return <PageHero eyebrow="انضم إلينا" title={<>كبر مع <strong>فالسريع.</strong></>} text="اختار الطريقة المناسبة للتواصل معنا حاليًا، وهنعلن عن نظام التقديم عند جاهزيته."><section className="section"><div className="grid two"><article className="join-card"><Users/><h2>التقديم قريبًا</h2><p>نظام التقديم للمندوبين والشركاء سيتم إطلاقه لاحقًا.</p><span className="status-pill">COMING SOON</span></article><article className="join-card"><MessageCircle/><h2>تواصل معنا للانضمام</h2><p>لو مهتم بالانضمام، تواصل معنا مباشرة عبر الدعم.</p><a className="btn primary" href={contactHref(CONTACTS[0])}><Phone/> تواصل الآن</a></article></div></section></PageHero>}
function Contact(){const phoneContacts=CONTACTS.filter(x=>x.type==="phone"); const whatsappContacts=CONTACTS.filter(x=>x.type==="whatsapp"); return <PageHero eyebrow="تواصل معنا" title={<>نحن <strong>قريبون منك.</strong></>} text="اختر رقم الدعم أو واتساب المناسب. يمكنك إضافة أكثر من رقم بسهولة من إعدادات الموقع لاحقًا."><section className="section contact-section"><h2 className="contact-title">الدعم والاتصال</h2><div className="grid two">{phoneContacts.map((c,i)=><a className="contact-card" key={i} href={contactHref(c)}><Phone/><div><b>{c.label}</b><span>{c.value}</span><small>اضغط للاتصال مباشرة</small></div></a>)}</div><h2 className="contact-title">واتساب</h2><div className="grid two">{whatsappContacts.map((c,i)=><a className="contact-card whatsapp" key={i} href={contactHref(c)} target="_blank" rel="noreferrer"><MessageCircle/><div><b>{c.label}</b><span>{c.value}</span><small>اضغط لفتح محادثة واتساب</small></div></a>)}</div>{SOCIALS.length>0&&<><h2 className="contact-title">تابعنا</h2><div className="social-list">{SOCIALS.map((s,i)=><a key={i} href={s.url} target="_blank" rel="noreferrer">{s.label}</a>)}</div></>}</section></PageHero>}
function Legal({title,type}:{title:string,type:"privacy"|"terms"}){const privacy=type==="privacy";return <><section className="page-hero legal-hero"><span className="eyebrow">FELSARE3</span><h1>{title}</h1><p>نسخة مبدئية قابلة للتحديث عند إطلاق الخدمات والأنظمة الإلكترونية.</p></section><section className="section legal-content">{privacy?<><h2>مقدمة</h2><p>نحترم خصوصية زوار موقع فالسريع. في المرحلة الحالية الموقع تعريفي ولا يتطلب إنشاء حساب أو إدخال بيانات شخصية إلا عند إضافة نماذج رسمية مستقبلًا.</p><h2>التواصل</h2><p>عند الضغط على رقم هاتف أو رابط واتساب، يتم فتح تطبيق الاتصال أو الخدمة الخارجية المختارة من جهازك.</p><h2>التحديثات</h2><p>سيتم تحديث هذه السياسة عند إطلاق نظام الحسابات أو الطلبات أو أي خدمات تتطلب معالجة بيانات.</p></>:<><h2>استخدام الموقع</h2><p>الموقع الحالي يقدم معلومات تعريفية عن مشروع فالسريع ووسائل التواصل المتاحة.</p><h2>المحتوى والخدمات</h2><p>الخدمات والمناطق ووسائل التواصل قد تتغير مع تطور المشروع، وسيتم تحديث الموقع وفقًا لذلك.</p><h2>التطبيق والطلبات</h2><p>أي نظام طلبات أو تطبيق إلكتروني سيتم الإعلان عن شروط استخدامه وسياساته عند إطلاقه رسميًا.</p></>}</section></>}

function PageHero({eyebrow,title,text,children}:{eyebrow:string,title:React.ReactNode,text:string,children:React.ReactNode}){return <><section className="page-hero"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></section>{children}<section className="cta"><h2>فالسريع… قريبًا أكثر.</h2><p>تابعنا لمعرفة آخر الأخبار والتحديثات.</p></section></>}

createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
